name: build-dev

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev


jobs:
  build-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx: [stable, mainline]
        module-type: [-add-module, --add-dynamic-module]
    container: centos:8
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          dnf -y install https://extras.getpagespeed.com/release-latest.rpm
          dnf -y --enablerepo=powertools install lastversion make gcc openssl-devel zlib-devel pcre-devel uthash-devel
      - name: Download NGINX ${{ matrix.nginx }}
        run: |
          lastversion download nginx:${{ matrix.nginx }}
          mkdir nginx-src
          tar zxf nginx-*.tar.gz --directory nginx-src --strip-components=1
      - name: Configure ${{ matrix.module-type }}
        run: |
          cd nginx-src
          ./configure ${{ matrix.module-type }}=..
      - name: Make
        run: |
          cd nginx-src
          make