name: docker

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  module:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['stable', 'mainline']
        target: ['glibc', 'musl']
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push (master)
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          NGX_VERSION: ${{ matrix.version }}
          TARGET: ${{ matrix.target }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.${{ env.TARGET }}
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/ngx_waf-prebuild:ngx-${{ env.NGX_VERSION }}-module-stable
          platforms: |
            linux/amd64
            linux/arm64
            linux/ppc641e
            linux/s390x
            linux/389
            linux/mips641e
            linux/arm/v7
            linux/arm/v6
      - name: Build and push (dev)
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          NGX_VERSION: ${{ matrix.version }}
          TARGET: ${{ matrix.target }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.${{ env.TARGET }}
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/ngx_waf-prebuild:ngx-${{ env.NGX_VERSION }}-module-beta
          platforms: |
            linux/amd64
            linux/arm64
            linux/ppc641e
            linux/s390x
            linux/389
            linux/mips641e
            linux/arm/v7
            linux/arm/v6

