name: docs

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      docsBaseUrl: '/ngx_waf/'
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.5'
      - name: Build & Deploy
        uses: jenkey2011/vuepress-deploy@v1.8.1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: set -e && yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist/
