name: docs

on: 
  push:
    branches:
      - master
      - dev
  pull_request:


jobs:
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: ${{ github.event_name != 'pull_request' }}
  #   steps:
  #     - uses: actions/checkout@v2
  #       with: 
  #         ref: ${{ github.ref }}
  #     - name: Install Nodejs
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.15.5'
  #     - name: Build & Deploy
  #       uses: jenkey2011/vuepress-deploy@master
  #       env:
  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  #         TARGET_BRANCH: gh-pages
  #         BUILD_SCRIPT: set -e && yarn && yarn docs:build
  #         BUILD_DIR: docs/.vuepress/dist/


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}
      - name: Install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.5'
      - name: Build
        run: |
          set -e
          sudo yarn
          sudo yarn docs:build
